"""add_verification_to_partner

Revision ID: c803519edf0d
Revises: 
Create Date: 2026-06-27 09:45:18.484982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c803519edf0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.execute("UPDATE partners SET is_verified = FALSE")
    op.alter_column('partners', 'is_verified', nullable=False)
    op.add_column('partners', sa.Column('verification_date', sa.DateTime(), nullable=True))
    op.drop_index('idx_price_items_partner_raw_name', table_name='price_items')
    op.alter_column('services', 'synonyms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'synonyms',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('idx_price_items_partner_raw_name', 'price_items', ['partner_id', 'service_name_raw'], unique=False)
    op.drop_column('partners', 'verification_date')
    op.drop_column('partners', 'is_verified')
    # ### end Alembic commands ###
